# Generated by Django 2.2.9 on 2020-07-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200708_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email_sent',
            new_name='confirm_email',
        ),
    ]
